---
spring:
  config:
    activate:
      on-profile: set1
  datasource:
    url: jdbc:mysql://devvydb-1.ccul8tlktijr.ap-northeast-2.rds.amazonaws.com:3306/devyyyyy
    username: admin
    password: tlstmdgur11
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  port: 8081
  shutdown: graceful
jwt:
  header: Authorization
  secret: 7ZWo6ruY66eM65Ok7Ja064KY6rCA64qURGV2eXl5eeybueyCrOydtO2KuOyXkOyEnOq/iOydhOydtOukhOuztOyEuOyalA==
  token-validity-in-seconds: 86400
---
spring:
  config:
    activate:
      on-profile: set2
  datasource:
    url: jdbc:mysql://devvydb-1.ccul8tlktijr.ap-northeast-2.rds.amazonaws.com:3306/devyyyyy
    username: admin
    password: tlstmdgur11
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
server:
  port: 8082
  shutdown: graceful
jwt:
  header: Authorization
  secret: 7ZWo6ruY66eM65Ok7Ja064KY6rCA64qURGV2eXl5eeybueyCrOydtO2KuOyXkOyEnOq/iOydhOydtOukhOuztOyEuOyalA==
  token-validity-in-seconds: 86400


